plugins {
    id 'com.android.application'
    id 'com.google.protobuf' version '0.9.5'
}
ext {
    protobufVersion = '3.25.3'
}
android {
    namespace "net.af0.sesame"

    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "net.af0.sesame"
        minSdkVersion 21
	targetSdk 35
        versionCode 28
        versionName "1.9"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

	externalNativeBuild {
            cmake {
                // Tells the linker to align segments to 16KB
                arguments "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
            }
        }
    }

    // This tells the installer not to compress native libs, 
    // which is required for 16KB alignment to work correctly
    packagingOptions {
        jniLibs {
            useLegacyPackaging = false
        }
    }
    if (System.getenv("KEYSTORE") != null) {
        signingConfigs {
            release {
                storeFile file(System.getenv("KEYSTORE"))
                keyAlias System.getenv("KEY_ALIAS")
                storePassword System.getenv("KEYSTORE_PASSWD")
                keyPassword System.getenv("KEYSTORE_PASSWD")
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (System.getenv("KEYSTORE") != null) {
                signingConfig signingConfigs.release
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding true
    }

}
   
apply plugin: 'com.android.application'


protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protobufVersion}"
    }
    plugins {
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java { option 'lite' }
            }
        }
    }
}

sourceSets {
    main.java.srcDirs +=  "${protobuf.generatedFilesBaseDir}/main/javalite"
    main.java.srcDirs += "$projectDir/src/main/proto"
}

processResources {
    exclude('**/*.proto')
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-fragment:2.7.7'
    implementation 'androidx.navigation:navigation-ui:2.7.7'
    implementation(group: 'net.zetetic', name: 'sqlcipher-android', version: '4.12.0')
    implementation(group: 'androidx.sqlite', name: 'sqlite', version: '2.2.0')
    implementation "com.google.protobuf:protobuf-javalite:${protobufVersion}"
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

}
